FROM node:12.18.3

RUN mkdir /usr/src/app

COPY package*.json ./
COPY ./lib ./lib/
COPY ./src/app/index.js ./src/app/
COPY ./src/app/build ./src/app/build/

RUN npm install

CMD [ "npm", "run", "start:app" ]