FROM node:12.18.3

RUN mkdir /usr/src/verifier-app

COPY package*.json ./
COPY ./lib ./lib/
COPY ./src/verifier-app/index.js ./src/verifier-app/
COPY ./src/verifier-app/build ./src/verifier-app/build/

RUN npm install

CMD [ "npm", "run", "start:verifier-app" ]